### ISSUE TITLE
Hoppers

### ISSUE THREAD

**Issue by Lunaphied** [andrepl/Autocrafter#1]
If you attempt to use hoppers with this, your recipe will be modified instead of having the items stacked properly. I have spent the past couple of days actually coding a plugin that does the exact same thing as your plugin. I didn't see your plugin in the search. I already have a fix implemented for the hopper issue. Would you be willing to team up? I was thinking of adding some more functionality than basic crafting to my plugin but I just started a few days ago. I have a slightly more readable recipe system that I could add in as well as the fix for hoppers going into the dropper.

**Comment by andrepl** [comment]
Can you explain how to reproduce this? I haven't had any issues using hoppers to feed the autocrafter.  I just tried another quick test feeding in 63 diamonds from a hopper and crafting 9 pairs of diamond leggings, everything seemed to go smoothly.  

I like to keep my plugins single-purpose so I don't know if I'd be interested in adding much more to this unless it really fits well.  This plugin was a bit of a hassle to get working right, so the code definitely needs some clean-up, but I'm not really interested in getting involved in any sort of partnership just yet, a pull request seems like a more appropriate first date :)

**Comment by Lunaphied** [comment]
Alright. I remember you from irc, I didn't actually test it myself, but I
couldn't find a place where your code did a test to make sure that empty
slots were not filled, maybe there is a difference that I didn't see. I am
just a little frazzled from the waste of coding that my past 3 days turned
out to be. I implemented this stuff almost exactly the same way.

**Comment by andrepl** [comment]
I know the feeling well :) 
Like i said feel free to submit any contributions and I'm more than willing to include them if they don't alter the overall mechanics too much.  I'm going to try and clean up the code this weekend as well.

**Comment by Lunaphied** [comment]
It was a different implementation that saved you from the problem. I
implemented it exactly like build craft with the stacking of items. I get a
bunch of errors in the inventory move item event handler when i run the
plugin though. I don't see any reason for the errors but i had to disable
the plugin. I could probably get you an error log soonish.

**Comment by andrepl** [comment]
Please do, I haven't had any reports of errors w/ it yet.

**Comment by Lunaphied** [comment]
ok
