### ISSUE TITLE
Issue with Item Frames

### ISSUE THREAD

**Issue by kreezxil** [andrepl/Autocrafter#2]
Having serious problems with the item frame. I had gotten it to work one time for a few days based on your information about permissions. I have added plugins since then and have tried my best to make sure the permissions don't get narfed up but alas I am at that spot again where your plugin is refusing allowing items to be placed in item frames.

Please take a look at my permissions file and tell me what I am doing wrong.

http://pastebin.ca/2370072

p.s. my perm level is owner.

**Comment by andrepl** [comment]
There's nothing wrong with your permissions, can you paste your config.yml?  Are you getting a message when you try to put the item into the frame? are there any error messages in the console?

**Comment by andrepl** [comment]
what permissions plugin is this?

**Comment by kreezxil** [comment]
there is no message, you right click and shift right click, it doesn't
matter, the item doesn't go in the frame, on the machine or anywhere. Also,
the item frames are refusing to drop off when you hit them with an axe, you
have to destroy what they are attached to.. :(

On Tue, Apr 30, 2013 at 10:03 AM, andrepl notifications@github.com wrote:

> There's nothing wrong with your permissions, can you paste your
> config.yml? Are you getting a message when you try to put the item into the
> frame? are there any error messages in the console?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrepl/Autocrafter/issues/2#issuecomment-17232749
> .

## 

Blogging about North Central Texas life in Bowie, TX! Come read about it at
www.BowieRocks.com!

**Comment by kreezxil** [comment]
using pex

On Tue, Apr 30, 2013 at 10:27 AM, andrepl notifications@github.com wrote:

> what permissions plugin is this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrepl/Autocrafter/issues/2#issuecomment-17234366
> .

## 

Blogging about North Central Texas life in Bowie, TX! Come read about it at
www.BowieRocks.com!

**Comment by kreezxil** [comment]
you can log onto my server at 69.162.69.10:25565 and i'll op you if you
need it.

On Tue, Apr 30, 2013 at 10:32 AM, Itscool Really itscoolreally@gmail.comwrote:

> using pex
> 
> On Tue, Apr 30, 2013 at 10:27 AM, andrepl notifications@github.comwrote:
> 
> > what permissions plugin is this?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/andrepl/Autocrafter/issues/2#issuecomment-17234366
> > .
> 
> ## 
> 
> Blogging about North Central Texas life in Bowie, TX! Come read about it
> at www.BowieRocks.com!

## 

Blogging about North Central Texas life in Bowie, TX! Come read about it at
www.BowieRocks.com!

**Comment by andrepl** [comment]
there is nothing in this plugin that would prevent you from breaking the frame.  I think we're looking at a conflict with another plugin possibly. can you list your other plugins?

**Comment by kreezxil** [comment]
just found the problem.

I using ultralogger and lately it's been throwing severe errors, I disabled
it and restarted the server, now the frames work again.

suggest listing ultralogger as a possible conflict.

Also if you want to mention my site as using your plugin feel free to do
so, except mention the website and not the server as I change hosts some
times.

The website is http://www.NoBabies.info/

My goal is to create a FTB setup completely server side in bukkit. No
client mods required.

So far so good and I really do like your plugin. :)

On Tue, Apr 30, 2013 at 10:43 AM, andrepl notifications@github.com wrote:

> there is nothing in this plugin that would prevent you from breaking the
> frame. I think we're looking at a conflict with another plugin possibly.
> can you list your other plugins?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrepl/Autocrafter/issues/2#issuecomment-17235207
> .

## 

Blogging about North Central Texas life in Bowie, TX! Come read about it at
www.BowieRocks.com!

**Comment by andrepl** [comment]
Excellent, glad its working now.  If UltraLogger is throwing errors, its probably not so much a conflict as a problem on their end.  If there's any other plugins you're looking for let me know, I've never personally played FTB or tekkit but I'm always looking for good plugin ideas and I like doing small single-purpose ones that add new functionality like this.

**Comment by kreezxil** [comment]
right now I'm working on the technology side of things like adding
factories, pipes and stuff. Currently I have Autosort chests interfaced to
quite a few things including your crafting table.

On Tue, Apr 30, 2013 at 11:07 AM, andrepl notifications@github.com wrote:

> Excellent, glad its working now. If UltraLogger is throwing errors, its
> probably not so much a conflict as a problem on their end. If there's any
> other plugins you're looking for let me know, I've never personally played
> FTB or tekkit but I'm always looking for good plugin ideas and I like doing
> small single-purpose ones that add new functionality like this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrepl/Autocrafter/issues/2#issuecomment-17236761
> .

## 

Blogging about North Central Texas life in Bowie, TX! Come read about it at
www.BowieRocks.com!
