### ISSUE TITLE
Pull items from Hopper

### ISSUE THREAD

**Issue by psiie** [andrepl/Autocrafter#3]
I love your plugin, and it makes crafting large items much easier. However it would be amazing if the dropper was able to load items from a hopper. I do not know if hoppers are supposed to be able to connect with droppers as they are both vanilla, but it you could look into this, this would be greatly appreciated.

**Comment by andrepl** [comment]
This works fine for me, did you try it?  I filled a hopper with diamonds and sticks, and fed it into an autocrafter making diamond swords, all worked as it should.

**Comment by psiie** [comment]
haha apparently I had two issues: I had the hopper pointed the wrong direction and I am accidentally powering the hoppers. If I power the autocrafter from the bottom using a redstone torch, it powers two blocks up unfortunately and this makes items not feel in. I have to make a 50/50 clock to get all phases of crafting to go through if I use the bottom powered method.

**Comment by andrepl** [comment]
I'm pretty sure I did the exact same thing while testing that during development :)
